--DDL DOCUMENT (TABLES) DATABASE BUSINESS ADMINISTRATOR
--CREATE DATABASE
CREATE DATABASE BUSINESS_ADMINISTRATOR
USE BUSINESS_ADMINISTRATOR

--CREATE INDEPENDIENT TABLES

--Status ([1]ACTIVE [0]INACTIVE)

CREATE TABLE TOOLS(
id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
object_name VARCHAR(255) UNIQUE NOT NULL,
quiantity NUMERIC(10) NOT NULL,
details TEXT NULL,
picture IMAGE NULL,
status INT NOT NULL DEFAULT 1
);

CREATE TABLE USERS(
id INT UNIQUE NOT NULL IDENTITY(1,1),
first_name VARCHAR(80) NOT NULL,
last_name VARCHAR(100) NOT NULL,
cellphone_number VARCHAR(15) UNIQUE NULL,
document VARCHAR(15) PRIMARY KEY NOT NULL,
email VARCHAR(255) UNIQUE NOT NULL,
user_type INT NOT NULL DEFAULT 2,
photo IMAGE NULL
);

CREATE TABLE DEALERS(
id INT PRIMARY KEY NOT NULL IDENTITY(1,1),
name VARCHAR(255) NOT NULL UNIQUE,
number_cellphone VARCHAR(15) NOT NULL,
number_phone VARCHAR(15) NULL,
address VARCHAR(255) NULL,
web VARCHAR(255) NULL,
contact_email VARCHAR(255) NULL,
picture IMAGE NULL,
status INT NOT NULL DEFAULT 1
);

CREATE TABLE BRANDS(
id INT PRIMARY KEY NOT NULL IDENTITY(1,1),
name VARCHAR(70) NOT NULL UNIQUE,
status INT NOT NULL DEFAULT 1
);

CREATE TABLE LINES(
id INT PRIMARY KEY NOT NULL IDENTITY(1,1),
name VARCHAR(70) NOT NULL UNIQUE,
status INT NOT NULL DEFAULT 1
);

CREATE TABLE SERVICES(
id INT PRIMARY KEY NOT NULL IDENTITY(1,1),
name VARCHAR(255) UNIQUE NOT NULL,
reference VARCHAR(255) UNIQUE NOT NULL,
barcode VARCHAR(255) UNIQUE NOT NULL,
price MONEY NOT NULL,
description TEXT NULL DEFAULT 'None',
status INT NOT NULL DEFAULT 1
);


--CREATE DEPENDENTS TABLES

CREATE TABLE CLIENTS(
id INT PRIMARY KEY NOT NULL IDENTITY(1,1),
document_user VARCHAR(15) NOT NULL
CONSTRAINT FK_document_user_CLIENTS FOREIGN KEY REFERENCES USERS(document) ON DELETE NO ACTION ON UPDATE NO ACTION,
balance MONEY NULL DEFAULT 0,
debt MONEY NULL DEFAULT 0,
status INT NOT NULL DEFAULT 1
);

CREATE TABLE EMPLOYEES(
id INT PRIMARY KEY NOT NULL IDENTITY(1,1),
document_user VARCHAR(15) NOT NULL
CONSTRAINT FK_document_user_EMPLOYEES FOREIGN KEY REFERENCES USERS(document) ON DELETE NO ACTION ON UPDATE NO ACTION,
nickname VARCHAR(30) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL,
status INT NOT NULL DEFAULT 1
--lack add the permissions
);

CREATE TABLE SESIONS(
id INT PRIMARY KEY NOT NULL IDENTITY(1,1),
id_employee INT NOT NULL
CONSTRAINT FK_id_employee_SESIONS FOREIGN KEY REFERENCES EMPLOYEES(id),
date_login DATETIME NOT NULL,
initial_cashregister MONEY NOT NULL,
date_logout DATETIME NULL,
final_cashregister MONEY NULL,
pass_tries INT NOT NULL DEFAULT '1'
);

CREATE TABLE PRODUCTS(
id INT PRIMARY KEY NOT NULL IDENTITY(1,1),
reference VARCHAR(255) NOT NULL UNIQUE,
name VARCHAR(255) NOT NULL UNIQUE,
barcode VARCHAR(255) NOT NULL UNIQUE,
stock NUMERIC(10) NOT NULL,
minimum_stock NUMERIC(10) NULL,
price MONEY NOT NULL,
description TEXT NULL,
id_dealer INT NOT NULL
CONSTRAINT FK_id_dealer_PRODUCTS FOREIGN KEY REFERENCES DEALERS(id),
id_brand INT NOT NULL
CONSTRAINT FK_id_brand_PRODUCTS FOREIGN KEY REFERENCES BRANDS(id),
id_line INT NOT NULL
CONSTRAINT FK_id_line_PRODUCTS FOREIGN KEY REFERENCES LINES(id),
product_image IMAGE NULL,
status INT NOT NULL DEFAULT 1
);

CREATE TABLE PURCHASES(
N_invoice INT PRIMARY KEY NOT NULL IDENTITY(1,1),
id_employee INT NOT NULL
CONSTRAINT FK_id_employee_PURCHASES FOREIGN KEY REFERENCES EMPLOYEES(id),
date DATETIME NOT NULL,
total_purchase MONEY NOT NULL
);

CREATE TABLE DETAILS_PURCHASE(
id INT PRIMARY KEY NOT NULL IDENTITY(1,1),
N_invoice INT NOT NULL
CONSTRAINT FK_N_invoice_DETAILS_PURCHASES FOREIGN KEY REFERENCES PURCHASES(N_invoice),
id_product INT NOT NULL
CONSTRAINT FK_id_product_DETAILS_PURCHASES FOREIGN KEY REFERENCES PRODUCTS(id),
id_dealer INT NOT NULL
CONSTRAINT FK_id_dealer_DETAILS_PURCHASES FOREIGN KEY REFERENCES DEALERS(id),
product_quantity NUMERIC(10) NOT NULL,
price_purchase MONEY NOT NULL, --PURCHASE UNITY
sub_total MONEY NOT NULL --(Product quantity*Price purchase)
);

CREATE TABLE SALES(
N_invoice INT PRIMARY KEY NOT NULL IDENTITY(1,1),
id_client INT NOT NULL
CONSTRAINT FK_id_client_SALES FOREIGN KEY REFERENCES CLIENTS(id),
id_employee INT NOT NULL
CONSTRAINT FK_id_employee_SALES FOREIGN KEY REFERENCES EMPLOYEES(id),
date DATE NOT NULL,
total_sale MONEY NOT NULL,
cash_recieved MONEY NOT NULL,
change MONEY NOT NULL
);

CREATE TABLE DETAILS_PRODUCT_SALES(
id_sale_product INT PRIMARY KEY NOT NULL IDENTITY(1,1),
N_invoice INT NOT NULL
CONSTRAINT FK_N_invoice_DETAILS_PRODUCT_SALES FOREIGN KEY REFERENCES SALES(N_invoice),
id_product INT NOT NULL
CONSTRAINT FK_id_product_DETAILS_PRODUCT_SALES FOREIGN KEY REFERENCES PRODUCTS(id),
amount NUMERIC(10) NOT NULL,
sub_total MONEY NOT NULL
);

CREATE TABLE DETAILS_SERVICE_SALES(
id_sale_service INT PRIMARY KEY NOT NULL IDENTITY(1,1),
N_invoice INT NOT NULL
CONSTRAINT FK_N_invoice_DETAILS_SERVICE_SALES FOREIGN KEY REFERENCES SALES(N_invoice),
id_service INT NOT NULL
CONSTRAINT FK_id_service_DETAILS_SERVICE_SALES FOREIGN KEY REFERENCES SERVICES(id),
amount NUMERIC(10) NOT NULL,
sub_total MONEY NOT NULL
);